version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/nexus-public
    environment:
      MAVEN_OPTS: -Xmx2700m
      OPENSSL_CONF: /

jobs:
  build:
    executor: my-executor
    steps:
      - checkout
      - run: mvn -U clean install
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  deploy-snapshot:
    executor: my-executor
    steps:
      - checkout
      - run:
          name: Deploy Snapshot
          command: |
            mvn -s .circleci/circleci.settings.xml deploy -DskipTests

workflows:
  build-deploy-snapshot:
    jobs:
      - build
      - deploy-snapshot:
          filters:
            branches:
              only: master
          requires:
            - build
